# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do

lane :refreshJenkinsKeychain do
  delete_keychain(name: "jenkins") if File.exists? File.expand_path("~/Library/Keychains/jenkins-db")
  create_keychain(
    name: "jenkins",
    password: "jenkins",
    timeout: false,
    lock_when_sleeps: false,
    unlock: true
  )
end
lane :matchPopulateJenkinsKeychain do
  # register_devices(devices_file: "./fastlane/devices.txt")

  # match(
  #   type: "adhoc",
  #   app_identifier: [
  #     "com.bulpros.test-jenkins"
  #   ]
  # )
   match(
     type: "development",
     app_identifier:"com.bulpros.test-jenkins",
      keychain_name: "login.keychain",
      keychain_password: "1234"
   )
  # match(
  #   type: "appstore",
  #   app_identifier: [
  #     "com.bulpros.test-jenkins"
  #   ]
  # )
end


  desc "Build application"
  lane :buildAppWithGym do |options|
    build_ios_app(
      scheme: "test jenkins",
      export_method: “development”,
      configuration: “Debug”,
      silent: true,
      clean: true,
      output_name: "test jenkins.ipa",
      xcargs: "-allowProvisioningUpdates",
      export_xcargs: "-allowProvisioningUpdates",
      export_options: {
        'signingStyle': 'automatic',
        'compileBitcode': false
      }
    )
  end
end
